#! /usr/bin/env bash

#This script will convert a SAM file into a BAM file. It will also sort and index the file, along with removing unmapped reads. Provide the number of threads as the second argument to run everything multithreaded."
#[usage] sam2bam filename.sam threads"

FILENAME=$(basename $1 .sam)
THREADS=$2

FILENAME=`echo "$1" | cut -d '.' -f1`

# convert SAM to BAM
samtools view -hb $1 -@$THREADS > $FILENAME.tmp.bam && rm $1

# sort the BAM
samtools view -h -F4 $FILENAME.tmp.bam -@$THREADS | samtools sort -m 16G -l0  -@$THREADS> $FILENAME.bam && rm $FILENAME.tmp.bam

# index sorted BAM
samtools index $FILENAME.bam -@$THREADS